language: c
compiler:
  - gcc
  - clang
before_script: 
- ls
- sudo apt-get update -qq >/dev/null 2>&1
- sudo apt-get install -qq gfortran  >/dev/null 2>&1
- sudo apt-get install -qq  gcc-multilib gfortran-multilib  >/dev/null 2>&1
- sudo apt-get install -qq liblapack-dev >/dev/null 2>&1
- curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | sudo bash 
script: ls
after_script: luajit -ltorch -e "torch.test()"
